### PR TITLE
Lint rule

### PR DESCRIPTION
**Pull request by zigen**
`$ npm run lint`でコードチェックします

---

This change is [Reviewable](https://reviewable.io/reviews/comozilla/parapara-canvas-editor/25)

### CODE REVIEW

**Comment by zigen** [comment]
#7 参照

**Comment by shundroid** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 24 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/25#-KFnCy6eGomjcs4cYocL:-KFnCy6eGomjcs4cYocM:170858135) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/e76d04881f61365591cc21a212acb5e87b8627e4/README.md#L24)):_
現在のmasterと内容が競合しているので、
fetchしてmergeしていただけませんでしょうか。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/25)_

**Comment by zigen** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 24 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/25#-KFnCy6eGomjcs4cYocL:-KFnE7oP7rs9mdNegxHy:1733621815) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/e76d04881f61365591cc21a212acb5e87b8627e4/README.md#L24)):_
conflictしてないよ？

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/25)_

**Comment by shundroid** [comment]
Reviewed 8 of 9 files at r1.
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 24 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/25#-KFnCy6eGomjcs4cYocL:-KFnENjyQ7dMtJYHxAcE:-340283951) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/e76d04881f61365591cc21a212acb5e87b8627e4/README.md#L24)):_
すみませんでした～。大丈夫でした～

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/25)_

**Comment by shundroid** [comment]
Reviewed 1 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/25)_

**Pull request merged**
