### PR TITLE
Canvasを1つにした

### PR DESCRIPTION
**Pull request by shundroid**
This change is [Reviewable](https://reviewable.io/reviews/comozilla/parapara-canvas-editor/60)

### CODE REVIEW

**Comment by shundroid** [comment]
@hrl7 さん、レビューおねがいします！

**Comment by zigen** [comment]
Reviewed 2 of 10 files at r4.
Review status: 2 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

_[js/frames-controller.js, line 6 [r4]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/60#-KGeXkuprq5gZNrQovuR:-KGeXkuqHaiycqWT434M:-1486367094) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/09d1ece643b85b13295c53521dd247db2b9643d3/js/frames-controller.js#L6)):_
Stateという名前, 本当に誤解を生みそう

---

_[js/observe-current-frame.js, line 3 [r4]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/60#-KGeSe_UKXIyXD3F_aGv:-KGeSe_UKXIyXD3F_aGw:1505966931) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/09d1ece643b85b13295c53521dd247db2b9643d3/js/observe-current-frame.js#L3)):_
observeは動詞なのでメソッド名にみえる。
FrameObserverとかの方がよい
もしくは, 別にクラスしなくてもいい

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/60)_

**Comment by zigen** [comment]
Reviewed 6 of 10 files at r4.
Review status: 6 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/60)_

**Comment by zigen** [comment]
Reviewed 2 of 10 files at r4.
Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/60)_

**Comment by zigen** [comment]
Reviewed 6 of 6 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[js/frames-controller.js, line 6 [r5]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/60#-KGfEqs5z6o22MVY47Mi:-KGfEqs5z6o22MVY47Mj:-155249633) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/4df3b933b81ed2db19cdc257fc8bec9250b4e199/js/frames-controller.js#L6)):_
currentFrameIdにPublisherを突っ込むと, なにやってるのか意味がわからない。
idには, 文字列なり数字なりが入っていると推測されやすい。
currentFrameIdには数字をいれて, setterでPublishするとかのほうがわかりやすそう。

---

_[js/frames-controller.js, line 29 [r5]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/60#-KGfFEhaDl_D2lH5iFUY:-KGfFEhaDl_D2lH5iFUZ:887741865) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/4df3b933b81ed2db19cdc257fc8bec9250b4e199/js/frames-controller.js#L29)):_
Idの中にdataがあると考えるのはすこし難しいと思う。直感的ではない。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/60)_

**Comment by zigen** [comment]
Reviewed 1 of 6 files at r5, 5 of 5 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/60)_

**Pull request merged**
