### PR TITLE
Sequence UI を動くようにした。

### PR DESCRIPTION
**Pull request by shundroid**
@hrl7 さん、よろしくお願いします！

P.S.

Assignee って、レビューする人っぽいです。

---

This change is [Reviewable](https://reviewable.io/reviews/comozilla/parapara-canvas-editor/75)

### CODE REVIEW

**Comment by zigen** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[js/frames-controller.js, line 36 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/75#-KGtPL5bTKGX0iKJY1i5:-KGtPL5bTKGX0iKJY1i6:-1655970486) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/7b2d4957b747e80fe28c3619992721f110c6d5bb/js/frames-controller.js#L36)):_
removeしつづけたあと, this.frames.lengthが0になると, this.getFrameByIdでエラーになります。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/75)_

**Comment by shundroid** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[js/frames-controller.js, line 36 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/75#-KGtPL5bTKGX0iKJY1i5:-KGtWSC1Ud6XsdqFnymq:220949004) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/7b2d4957b747e80fe28c3619992721f110c6d5bb/js/frames-controller.js#L36)):_
あ、ほんとだ。残りフレーム数が１つの時は消せないようにします。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/75)_

**Comment by shundroid** [comment]
Review status: 9 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

_[js/frames-controller.js, line 36 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/75#-KGtPL5bTKGX0iKJY1i5:-KGtaa7oHhlo-YZ6S5bB:-1483943037) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/7b2d4957b747e80fe28c3619992721f110c6d5bb/js/frames-controller.js#L36)):_
直しました！

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/75)_

**Comment by zigen** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/75)_

**Pull request merged**
