### PR TITLE
Fix lint rule

### PR DESCRIPTION
**Pull request by zigen**
- http://eslint.org/docs/rules/ の Best PracticesとVariablesとStylistic Issuesに関する項目を追加した
- それにともなって, 既存のコードもいくつか修正した

---

This change is [Reviewable](https://reviewable.io/reviews/comozilla/parapara-canvas-editor/46)

### CODE REVIEW

**Comment by dadaa** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

_[.eslintrc.json, line 48 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46#-KG51KGuLhllj0zy-8Fh:-KG51KGuLhllj0zy-8Fi:725927386) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/a81e2e1b1183d4672785d6fd015b4739c6bb806d/.eslintrc.json#L48)):_
行末に空白文字入っちゃってるよ

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46)_

**Comment by dadaa** [comment]
Review status: 0 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

_[.eslintrc.json, line 61 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46#-KG51qJFQqFLAToWNc3c:-KG51qJG10SK_zYAF0t6:172589795) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/a81e2e1b1183d4672785d6fd015b4739c6bb806d/.eslintrc.json#L61)):_
ここと

---

_[.eslintrc.json, line 129 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46#-KG51ttCmSzKmtWQXZPH:-KG51ttCmSzKmtWQXZPI:5567013) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/a81e2e1b1183d4672785d6fd015b4739c6bb806d/.eslintrc.json#L129)):_
ここ

---

_[.eslintrc.json, line 130 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46#-KG51vbq_B88gI14qvoY:-KG51vbq_B88gI14qvoZ:5567013) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/a81e2e1b1183d4672785d6fd015b4739c6bb806d/.eslintrc.json#L130)):_
ここ

---

_[.eslintrc.json, line 131 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46#-KG51wfvOws_rxB8iBav:-KG51wfvOws_rxB8iBaw:5567013) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/a81e2e1b1183d4672785d6fd015b4739c6bb806d/.eslintrc.json#L131)):_
ここ

---

_[.eslintrc.json, line 133 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46#-KG51y9ZzJSZudmMzM5v:-KG51y9ZzJSZudmMzM5w:5567013) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/a81e2e1b1183d4672785d6fd015b4739c6bb806d/.eslintrc.json#L133)):_
ここ

---

_[.eslintrc.json, line 179 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46#-KG522mE17Gw1gUXnqNC:-KG522mE17Gw1gUXnqND:5567013) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/a81e2e1b1183d4672785d6fd015b4739c6bb806d/.eslintrc.json#L179)):_
ここ

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46)_

**Comment by dadaa** [comment]
Review status: 0 of 6 files reviewed at latest revision, 9 unresolved discussions.

---

_[gulpfile.js, line 37 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46#-KG52D9bVqvUpDVlcYRO:-KG52D9bVqvUpDVlcYRP:810041153) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/a81e2e1b1183d4672785d6fd015b4739c6bb806d/gulpfile.js#L37)):_
ごめん，このコメントどういう意味です？

---

_[js/color-picker.js, line 8 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46#-KG52XMWYLm65JB3H3UM:-KG52XMXPysiLPY25czs:1254947291) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/a81e2e1b1183d4672785d6fd015b4739c6bb806d/js/color-picker.js#L8)):_
この行は，もとあったところの方が妥当かと思います

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46)_

**Comment by shundroid** [comment]
Review status: 0 of 6 files reviewed at latest revision, 10 unresolved discussions.

---

_[gulpfile.js, line 23 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46#-KG52cWHzyybOtgQrez5:-KG52cWHzyybOtgQrez6:1659857468) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/a81e2e1b1183d4672785d6fd015b4739c6bb806d/gulpfile.js#L23)):_
ここの{の前にスペースがないですー

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46)_

**Comment by dadaa** [comment]
Review status: 0 of 6 files reviewed at latest revision, 12 unresolved discussions.

---

_[js/color-picker.js, line 24 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46#-KG52hb-fikC_gQNczU3:-KG52hb0KBXksROPmzcE:-1473865009) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/a81e2e1b1183d4672785d6fd015b4739c6bb806d/js/color-picker.js#L24)):_
この空白行いらないんじゃない？

---

_[js/color-picker.js, line 26 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46#-KG52k5ferV1BSNKSnPk:-KG52k5ferV1BSNKSnPl:1056052214) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/a81e2e1b1183d4672785d6fd015b4739c6bb806d/js/color-picker.js#L26)):_
この行も

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46)_

**Comment by shundroid** [comment]
Review status: 0 of 6 files reviewed at latest revision, 12 unresolved discussions.

---

_[gulpfile.js, line 37 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46#-KG52D9bVqvUpDVlcYRO:-KG52ia2SGo10UhrrBU4:2029050764) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/a81e2e1b1183d4672785d6fd015b4739c6bb806d/gulpfile.js#L37)):_
これ追加したのぼくです。
たしかに謎だ。
一つ上の行で、最初は、./js/**と書いていたのですが、
それを./js/build/**に変えた理由を書いています。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46)_

**Comment by dadaa** [comment]
Review status: 0 of 6 files reviewed at latest revision, 13 unresolved discussions.

---

_[js/frame.js, line 2 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46#-KG530gDVF_YAs0HoirI:-KG530gEs8xpFR--rkBX:-1083245032) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/a81e2e1b1183d4672785d6fd015b4739c6bb806d/js/frame.js#L2)):_
コードとコメントで整合性がとれていないみたい

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46)_

**Comment by shundroid** [comment]
Review status: 0 of 6 files reviewed at latest revision, 14 unresolved discussions.

---

_[js/main.js, line 22 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46#-KG53Wq_iozAmnw-vycc:-KG53Wq_iozAmnw-vycd:413475049) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/a81e2e1b1183d4672785d6fd015b4739c6bb806d/js/main.js#L22)):_
というか、ここは変数にする必要が無いかもです。

``` js
["red", "orange", "yellow", "lightgreen", "green","..."].forEach(color => {
  colorPicker.addPalette(color);
});
```

これでも十分わかりやすいかも

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46)_

**Comment by shundroid** [comment]
Review status: 0 of 6 files reviewed at latest revision, 14 unresolved discussions.

---

_[js/frame.js, line 2 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46#-KG530gDVF_YAs0HoirI:-KG544CI6yD40CxiICrp:-814276516) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/a81e2e1b1183d4672785d6fd015b4739c6bb806d/js/frame.js#L2)):_
あら・・
ここのコメントはなしでいいかもですね。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46)_

**Comment by dadaa** [comment]
Review status: 0 of 6 files reviewed at latest revision, 14 unresolved discussions.

---

_[gulpfile.js, line 37 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46#-KG52D9bVqvUpDVlcYRO:-KG54CzmegU7W6M7ciDw:1343944462) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/a81e2e1b1183d4672785d6fd015b4739c6bb806d/gulpfile.js#L37)):_
必要なさそうなら，削除しましょうか

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46)_

**Comment by shundroid** [comment]
Review status: 0 of 6 files reviewed at latest revision, 14 unresolved discussions.

---

_[gulpfile.js, line 37 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46#-KG52D9bVqvUpDVlcYRO:-KG54Q2dyrHnY2rO_KFf:1070358944) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/a81e2e1b1183d4672785d6fd015b4739c6bb806d/gulpfile.js#L37)):_
そうですね。必要ないかも。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46)_

**Comment by dadaa** [comment]
Review status: 0 of 6 files reviewed at latest revision, 14 unresolved discussions.

---

_[js/frame.js, line 2 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46#-KG530gDVF_YAs0HoirI:-KG54r4FSC9sWyf1WtbF:-402094368) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/a81e2e1b1183d4672785d6fd015b4739c6bb806d/js/frame.js#L2)):_
少なくとも appendChild してないみたいよ

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46)_

**Comment by shundroid** [comment]
Review status: 0 of 6 files reviewed at latest revision, 14 unresolved discussions.

---

_[js/frame.js, line 2 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46#-KG530gDVF_YAs0HoirI:-KG552lEaNaAr9UEbHm1:-565468743) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/a81e2e1b1183d4672785d6fd015b4739c6bb806d/js/frame.js#L2)):_
そうなんです。
昔はappendChildする関数と別で、その後一緒にしたのですが、
その後別になりました。というのも、appendChildする部分はFramesControllerの役割かなと

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46)_

**Comment by dadaa** [comment]
Review status: 0 of 6 files reviewed at latest revision, 15 unresolved discussions.

---

_[js/main.js, line 33 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46#-KG55RQEmLVPVl-Wxb6b:-KG55RQF3MZTJWcSqmsk:-910853767) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/a81e2e1b1183d4672785d6fd015b4739c6bb806d/js/main.js#L33)):_
今回の修正とは関係ないけど，ここ一行でいいと思います．
colorPicker = new ColorPicker(document.getElementById("menu-colors"), "red");
mozilla 的には 80 文字以上になるようなら，改行をしかるべきところに入れて，80 文字を越えないようにしています

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46)_

**Comment by zigen** [comment]
Review status: 0 of 6 files reviewed at latest revision, 15 unresolved discussions.

---

_[gulpfile.js, line 23 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46#-KG52cWHzyybOtgQrez5:-KG5HWVdJShxpdRQMsWx:59339513) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/a81e2e1b1183d4672785d6fd015b4739c6bb806d/gulpfile.js#L23)):_
eslintのルールが間違ってるなぁ。なおしますー

---

_[js/frame.js, line 2 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46#-KG530gDVF_YAs0HoirI:-KG5GzusE5OmCP-ziaJh:251497616) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/a81e2e1b1183d4672785d6fd015b4739c6bb806d/js/frame.js#L2)):_
そのへんも修正しますー

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46)_

**Comment by zigen** [comment]
Reviewed 1 of 7 files at r1, 3 of 6 files at r2.
Review status: 3 of 6 files reviewed at latest revision, 15 unresolved discussions.

---

_[js/color-picker.js, line 8 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46#-KG52XMWYLm65JB3H3UM:-KGBvu1ggHmEIjLXEivr:1942374715) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/a81e2e1b1183d4672785d6fd015b4739c6bb806d/js/color-picker.js#L8)):_
そうですね, createElementだけ戻します
宣言は上のままにしておきたいです。
http://eslint.org/docs/rules/vars-on-top

---

_[js/main.js, line 22 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46#-KG53Wq_iozAmnw-vycc:-KGBtLNgD6uVOy8fs-Ng:-1701255482) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/a81e2e1b1183d4672785d6fd015b4739c6bb806d/js/main.js#L22)):_
なんの為の配列かわかるといいかなと思ったので変えてみました
今後, コードが増える事を考えて, 変数に切り出しておくべきかとおもいますー

http://eslint.org/docs/rules/no-magic-numbers

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46)_

**Comment by shundroid** [comment]
Reviewed 4 of 6 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/46)_

**Pull request merged**
