### PR TITLE
drawingConfiguration、ModelとViewを分ける

### PR DESCRIPTION
**Pull request by shundroid**
Work in progress 中です。
- [x] ColorPicker を分ける
- [x] LineWidthPicker を分ける
- [x] SequencePanel はどうしよう・・
  - とりあえず ViewConfiguration 内に入れたい。
- [x] Menuは ViewConfiguration 内に入れる
- [x] PaintManager

---

This change is [Reviewable](https://reviewable.io/reviews/comozilla/parapara-canvas-editor/65)

### CODE REVIEW

**Comment by zigen** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[js/view-configuration.js, line 4 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/65#-KGfpD7GmJgkTwI-alXS:-KGfpD7Kwj8phD8j-Cje:1210910326) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/e34c94c0a515750613aad67889952733a8aa6698/js/view-configuration.js#L4)):_
ViewConfigurationだと, なにを設定するのかわからなくなりそう

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/65)_

**Comment by shundroid** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[js/view-configuration.js, line 4 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/65#-KGfpD7GmJgkTwI-alXS:-KGfsCe2aocDGmzrIJmX:974751367) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/e34c94c0a515750613aad67889952733a8aa6698/js/view-configuration.js#L4)):_
たしかに・・
Viewたちを「まとめる」のと「管理する」という意味なんですよねー
とりあえず `ViewManager` にしておきますー

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/65)_

**Comment by zigen** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/65)_

**Comment by zigen** [comment]
Reviewed 2 of 9 files at r1, 2 of 6 files at r2, 9 of 9 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/65)_

**Comment by shundroid** [comment]
@hrl7 js-dev へのマージ、よろしくお願いします。

**Comment by zigen** [comment]
Reviewed 2 of 9 files at r1, 2 of 6 files at r2, 9 of 9 files at r3, 5 of 9 files at r4, 4 of 4 files at r5.
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

_[js/main.js, line 26 [r5]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/65#-KGmdljJY-4vnOZJaujd:-KGmdljK90AkVYMbjEXy:-2032698659) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/abf25da46add1e7588ecf889f9c100e907ee4285/js/main.js#L26)):_
どちらも#canvasなので, const canvas = document.getElementById('canvas') してからcanvasを渡したほうがいいと思います

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/65)_

**Comment by zigen** [comment]
Reviewed 2 of 9 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/65)_

**Comment by shundroid** [comment]
Review status: 9 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

_[js/main.js, line 26 [r5]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/65#-KGmdljJY-4vnOZJaujd:-KGoIWayEthN3FFc3_ZY:-1483996028) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/abf25da46add1e7588ecf889f9c100e907ee4285/js/main.js#L26)):_
直しました。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/65)_

**Comment by zigen** [comment]
Reviewed 1 of 9 files at r1, 2 of 2 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/65)_

**Pull request merged**
