### PR TITLE
fixed #9 再生・停止機能を追加

### LINKED ISSUE #9: 再生 ・ 停止機能
## やること
- [x] Play モードを追加する
  - [x] 描く機能のロック
  - [x] Play時のUIの変更（menu-side-btnを停止ボタンに）
- [x] 再生・停止
  - [x] Player という別途クラスを用意して、PlayメソッドとStopメソッドを追加
  - [x] Stop? Pause?
  - [x] Play メソッド
    - [x] setInterval による currentFrame の切り替え
  - [x] Stop メソッド
    - [x] clearTimeout する
- [x] 再生・停止（UI）
  - [x] UI から再生できるように
    - [x] 再生ボタンのリスナーを設置
  - [x] UI から停止できるように
    - [x] menu-side-btn を停止ボタンに変化させる
      - [x] Menu クラスで menu-side-btn のモードを変更するメソッドを追加して行ってほしい
  - #8 が終わってからになるかな

提案があれば[Wikiまで](https://github.com/comozilla/Parapara-Canvas-Editor/wiki/%239-%E5%AE%8C%E4%BA%86%E3%81%BE%E3%81%A7%E3%81%AE%E6%B5%81%E3%82%8C)よろしくお願いします。
## 仕様

再生する Frameは、frameId が 0 のものから再生。
停止したら、前作業していた Frame に戻す。

### PR DESCRIPTION
**Pull request by shundroid**
@hrl7 さん、よろしくお願いします。
#9

---

This change is [Reviewable](https://reviewable.io/reviews/comozilla/parapara-canvas-editor/86)

### CODE REVIEW

**Comment by zigen** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[index.html, line 15 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/86#-KGwsHCO1_NvQ8VvuYqQ:-KGwsHCP-8QSG3aA9eec:1492483718) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/1c71f9494cf143691a447b57185a883934638ae5/index.html#L15)):_
今回のPRとはちがうけど, play-btnの方が分かりやすい気がする

---

_[js/view/menu-view.js, line 5 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/86#-KGwrBtsHmtJLi-2yyJs:-KGwrBtsHmtJLi-2yyJt:1684757031) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/1c71f9494cf143691a447b57185a883934638ae5/js/view/menu-view.js#L5)):_
この変数, なにを示しているのかいまいち分からない...
PauseModeってなんだ...

---

_[js/view/menu-view.js, line 6 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/86#-KGwrYuAYpxDjcRw54Ps:-KGwrYuBO6n-GNO0hM8r:-646999606) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/1c71f9494cf143691a447b57185a883934638ae5/js/view/menu-view.js#L6)):_
このupdateCollapsibleButtonMode()ってメソッド, this.isCollapsibleButtonPauseModeを変更したあとに毎回呼び出してるけど, setCollapsibleButtonMode( true/false ) みたいな形にせずに, 分けている理由はあるのかな？

---

_[js/view/menu-view.js, line 30 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/86#-KGwqRRKbQtDRiXEvm-m:-KGwqRRKbQtDRiXEvm-n:-327620759) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/1c71f9494cf143691a447b57185a883934638ae5/js/view/menu-view.js#L30)):_
この3行, なんのためにやっているのかよく分からない...
this.toggleMenu()ってすると, Open/Closeが切り替わるというのが分かり易い

---

_[js/view/menu-view.js, line 56 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/86#-KGwqxUHFbaZRCu3GJQd:-KGwqxUHFbaZRCu3GJQe:-1635287941) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/1c71f9494cf143691a447b57185a883934638ae5/js/view/menu-view.js#L56)):_
innerHTMLにいれちゃうのってどうなんだろうか。
classList.add/removeだとだめかね？
あとで調べてみる

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/86)_

**Comment by shundroid** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[js/view/menu-view.js, line 5 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/86#-KGwrBtsHmtJLi-2yyJs:-KGyHN2IrrkOuRiT8owm:205442005) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/1c71f9494cf143691a447b57185a883934638ae5/js/view/menu-view.js#L5)):_
collapsibleButtonが、再生中モードになっているかを表しています。
isPlaying でもいいような・・

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/86)_

**Comment by shundroid** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[js/view/menu-view.js, line 6 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/86#-KGwrYuAYpxDjcRw54Ps:-KGyHdc4iCYPzVjcM5xY:457359812) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/1c71f9494cf143691a447b57185a883934638ae5/js/view/menu-view.js#L6)):_
一緒にします。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/86)_

**Comment by shundroid** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[js/view/menu-view.js, line 30 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/86#-KGwqRRKbQtDRiXEvm-m:-KGyHrqZkqStZ4OL3ql5:1149387420) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/1c71f9494cf143691a447b57185a883934638ae5/js/view/menu-view.js#L30)):_
上の this.toggleMenu(...) は、何であるんだろう・・多分消し忘れかな・・
this.isOpen の変更も、this.toggleMenuに入れます。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/86)_

**Comment by shundroid** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[js/view/menu-view.js, line 30 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/86#-KGwqRRKbQtDRiXEvm-m:-KGyJKZTt19L_Edvl84e:38712875) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/1c71f9494cf143691a447b57185a883934638ae5/js/view/menu-view.js#L30)):_
@hrl7 
そうだった。でも、this.toggleMenuには、引数で、切り替えるのではなく、常に隠すだけをしているところもあるので、
とりあえず、this.setMenuVisible にしておきます。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/86)_

**Comment by shundroid** [comment]
Review status: 6 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

_[index.html, line 15 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/86#-KGwsHCO1_NvQ8VvuYqQ:-KGyJyCM5I77_kEQUaCL:-98954666) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/1c71f9494cf143691a447b57185a883934638ae5/index.html#L15)):_
それも直します。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/86)_

**Comment by shundroid** [comment]
Review status: 4 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

_[js/view/menu-view.js, line 56 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/86#-KGwqxUHFbaZRCu3GJQd:-KGyLEYpp80YPet9rRKb:998540637) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/1c71f9494cf143691a447b57185a883934638ae5/js/view/menu-view.js#L56)):_
@hrl7 
#88 に書きましたが、Reactを使うとかも手かも・・（今回のPRではしませんが）
そうか！ menu-collapsible-btn に、直接 fa-pause fa-cog クラスを追加すればいいのかもです。
menu-collapse-btn-pause とかにして、:before で content 追加したいけど、html タグが反映されないんです・・
どうしましょう。直接 fa-cog とかをつけますかね。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/86)_

**Comment by zigen** [comment]
Reviewed 3 of 4 files at r2.
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/86)_

**Comment by zigen** [comment]
Reviewed 1 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[js/view/menu-view.js, line 56 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/86#-KGwqxUHFbaZRCu3GJQd:-KGyXg3sCN1aL2bWyJLz:1447960749) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/1c71f9494cf143691a447b57185a883934638ae5/js/view/menu-view.js#L56)):_
こういうのじゃだめかね？最初から`<i class="fa fa-pause"></i>` とかしておいて

```
MenuView.prototype.setCollapsibleButtonMode = function(isPlaying) {
  const icon = document.querySelector("#menu-collapsible-btn i");
  this.isPlaying = isPlaying
  if (isPlaying) {
    icon.classList.add("fa-pause")
    icon.classList.remove("fa-cog")
  } else {
    icon.classList.add("fa-cog")
    icon.classList.remove("fa-pause")
  }
};
```

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/86)_

**Comment by shundroid** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[js/view/menu-view.js, line 56 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/86#-KGwqxUHFbaZRCu3GJQd:-KGyYPwCWKjlHEJV6qCV:-991544753) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/1c71f9494cf143691a447b57185a883934638ae5/js/view/menu-view.js#L56)):_
おお！そうしておきます！

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/86)_

**Comment by shundroid** [comment]
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

_[js/view/menu-view.js, line 56 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/86#-KGwqxUHFbaZRCu3GJQd:-KGy_rShrIdBLb9Otz_5:-782929105) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/1c71f9494cf143691a447b57185a883934638ae5/js/view/menu-view.js#L56)):_
@hrl7 直しました。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/86)_

**Comment by zigen** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/86)_

**Pull request merged**
