### PR TITLE
fixed #76 Sequence-Viewにアニメーションを追加

### LINKED ISSUE #76: SequenceEditorにアニメーションを付ける
- Frame追加時
- Frame削除時
- Frame移動時

現状ではアニメーションの実装が少しむずかしい。
なぜなら、フレームを追加したあと、FramesControllerと同期するため、
一度すべて消してから、追加しているからである。
差分をうまくとれるようにしないと・・

### PR DESCRIPTION
**Pull request by shundroid**
#76

レビューをよろしくお願いします。

---

This change is [Reviewable](https://reviewable.io/reviews/comozilla/parapara-canvas-editor/102)

### CODE REVIEW

**Comment by dadaa** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[js/view/sequence-view.js, line 89 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/102#-KHFGhr5cJrBngBnzNnl:-KHFGhr6Ee7RW9DvzK39:516833722) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/a17f4912736c30ffbad43754067f96f2180c3807/js/view/sequence-view.js#L89)):_

> ``` JavaScript
>     { transformOrigin: "0px 100%", transform: "scaleY(1)" }],
>     { direction: "alternate", duration: 250,
>       fill: "both", easing: "ease-in-out" });
> ```

animate のところ，結構共通するところがあるので，関数化してみてはどうでしょう？
たとえば，こんな感じ?
SequencePanel.prototype.appendEffect(element, keyframes) {
  element.animate(keyframes, { direction: "alternate", duration: 250, fill: "both", easing: "ease-in-out" });
}
使い方としては，
this.appendEffect(newFrame, [{ transformOrigin: "0px 0px", transform: "scaleY(0)" }, { transformOrigin: "0px 100%", transform: "scaleY(1)" }]);

インデントは適当に直して〜

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/102)_

**Comment by shundroid** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[js/view/sequence-view.js, line 89 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/102#-KHFGhr5cJrBngBnzNnl:-KHFIWBBJjXyCjHm-yVm:49781383) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/a17f4912736c30ffbad43754067f96f2180c3807/js/view/sequence-view.js#L89)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> animate のところ，結構共通するところがあるので，関数化してみてはどうでしょう？
> たとえば，こんな感じ?
> SequencePanel.prototype.appendEffect(element, keyframes) {
>   element.animate(keyframes, { direction: "alternate", duration: 250, fill: "both", easing: "ease-in-out" });
> }
> 使い方としては，
> this.appendEffect(newFrame, [{ transformOrigin: "0px 0px", transform: "scaleY(0)" }, { transformOrigin: "0px 100%", transform: "scaleY(1)" }]);
> 
> インデントは適当に直して〜</details>
> そうします～！

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/102)_

**Comment by shundroid** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[js/view/sequence-view.js, line 89 [r1]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/102#-KHFGhr5cJrBngBnzNnl:-KHFKcLdxKxDX9qngJDB:1697602098) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/a17f4912736c30ffbad43754067f96f2180c3807/js/view/sequence-view.js#L89)):_
<details><summary>

<i>Previously, shundroid wrote…</i></summary>



> そうします～！</details>
> @dadaa
> アニメーションについてですが、「消す・作る」「移動する」の２つにまとめることでより効率的に書けるかと思ったため、
> ２つのメソッドに分けました。
> ちなみに、この変更によって、フレームを閉じる時のアニメーションの transformOrigin も修正しました。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/102)_

**Comment by dadaa** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

_[js/view/sequence-view.js, line 86 [r2]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/102#-KHFOPVGjB8xvV7LsYmh:-KHFOPVHzEkTBEVfNU-Z:-1171714431) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/07b7ce46e314e1d6db4250ae9c19bd76059a05f8/js/view/sequence-view.js#L86)):_

> ``` JavaScript
>   frame.animate(
>     [{ transformOrigin: "0px 0px", transform: "scaleY(0)" },
>     { transformOrigin: "0px 100%", transform: "scaleY(1)" }],
> ```

細かいけど，ここのブラケット "{" は上のブラケットと合わせた方が，意味的にわかりやすくなりそうです
スペース１個付け足してください

---

_[js/view/sequence-view.js, line 92 [r2]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/102#-KHFTCCuod4DPMm2zTtF:-KHFTCCuod4DPMm2zTtG:-2048716732) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/07b7ce46e314e1d6db4250ae9c19bd76059a05f8/js/view/sequence-view.js#L92)):_

> ``` JavaScript
> SequencePanel.prototype.appendMoveFrameEffect = function(frame, isMoveDown, frameHeight) {
>   frame.animate(
>     [{ transform: `translateY(${isMoveDown ? "" : "-"}${frameHeight})` },
> ```

ここ，ちょっと読みづらいから，変数に入れちゃったらどうでしょ
let beginningValue = isMoveDown ? frameHeight : -frameHeight;

---

_[js/view/sequence-view.js, line 93 [r2]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/102#-KHFOZXDGltwnX5LBM0Y:-KHFOZXDGltwnX5LBM0Z:172589821) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/07b7ce46e314e1d6db4250ae9c19bd76059a05f8/js/view/sequence-view.js#L93)):_

> ``` JavaScript
>   frame.animate(
>     [{ transform: `translateY(${isMoveDown ? "" : "-"}${frameHeight})` },
>     { transform: "translateY(0px)" }],
> ```

ここも

---

_[js/view/sequence-view.js, line 129 [r2]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/102#-KHFSnxZ92oESH797vGe:-KHFSnxZ92oESH797vGf:-1760252022) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/07b7ce46e314e1d6db4250ae9c19bd76059a05f8/js/view/sequence-view.js#L129)):_

> ``` JavaScript
>   let index = 0;
>   while (typeof (
>         childNode = children[index + disableFrameCount]) !== "undefined") {
> ```

ここも，ちょっと読みづらいすねぇ，，
while (
  typeof (childNode = children[index + disableFrameCount]) !== "undefined") {
の方が読み易いかなぁ

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/102)_

**Comment by shundroid** [comment]
@dadaa 直しました！ご確認よろしくお願いします。

<details><summary>

<i>Previously, shundroid wrote…</i></summary>



> #### fixed #76 Sequence-Viewにアニメーションを追加
> 
> #76 
> 
> レビューをよろしくお願いします。
> 
> </details>

---

Review status: 1 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/102#-:-KHJjmQ9-tsIddqJQjoU:23132212)_

**Comment by dadaa** [comment]
Review status: 1 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

_[js/frames-controller.js, line 35 [r3]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/102#-KHJkIziZD4H4jFFdele:-KHJkIzj4fPqbEL9jmSX:-1310121041) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/660203997999b4befb104b1bf32d176044759bfa/js/frames-controller.js#L35)):_

> ``` JavaScript
> };
> 
> FramesController.prototype.remove = function(id) {
> ```

変更の箇所とは違うけど，この id って，frame の id です？
だとすると，他のメソッドでは frameId という名前の引数になっているので，あわせておきたいですね

---

_[js/view/sequence-view.js, line 92 [r2]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/102#-KHFTCCuod4DPMm2zTtF:-KHJl49KhZB8Z6yyRjRJ:1973513421) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/07b7ce46e314e1d6db4250ae9c19bd76059a05f8/js/view/sequence-view.js#L92)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> ここ，ちょっと読みづらいから，変数に入れちゃったらどうでしょ
> let beginningValue = isMoveDown ? frameHeight : -frameHeight;
> </details>
> こうよー
> let beginningValue = isMoveDown ? frameHeight : -frameHeight;
> で，
> [{ transform: `translateY(${beginningValue}` },

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/102)_

**Comment by shundroid** [comment]
Review status: 1 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

_[js/frames-controller.js, line 35 [r3]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/102#-KHJkIziZD4H4jFFdele:-KHJlWmZiYgv9IHUuZpK:-172380418) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/660203997999b4befb104b1bf32d176044759bfa/js/frames-controller.js#L35)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> 変更の箇所とは違うけど，この id って，frame の id です？
> だとすると，他のメソッドでは frameId という名前の引数になっているので，あわせておきたいですね</details>
> わかりました。そうします。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/102)_

**Comment by dadaa** [comment]
Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/102)_

**Pull request merged**
