### PR TITLE
Thumbnail #77

### PR DESCRIPTION
**Pull request by nakamurataichi**
This change is [Reviewable](https://reviewable.io/reviews/comozilla/parapara-canvas-editor/93)

### CODE REVIEW

**Comment by dadaa** [comment]
Reviewed 2 of 5 files at r2, 1 of 2 files at r3.
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

_[js/frames-controller.js, line 17 [r3]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/93#-KHA-CEIUDWUU9NlR-Kg:-KHA-CEJY-xCQZ3wyiXQ:-548120011) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/905fcf41d6873685417647a73ad4e32dd25e8f98/js/frames-controller.js#L17)):_
updateCurrentFrameImageData
という function 名が素直かも

---

_[js/frames-controller.js, line 18 [r3]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/93#-KHA-ZdOXI0H4RtllHh7:-KHA-ZdOXI0H4RtllHh8:638497960) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/905fcf41d6873685417647a73ad4e32dd25e8f98/js/frames-controller.js#L18)):_
ここでやっているのは，current frame に対する操作なので，beforeFrame は適切ではないように思います

---

_[js/view/sequence-view.js, line 76 [r3]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/93#-KHA3wcXiCoNcQdAPPAh:-KHA3wcXiCoNcQdAPPAi:1532238709) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/905fcf41d6873685417647a73ad4e32dd25e8f98/js/view/sequence-view.js#L76)):_
this.framesController.currentFrameId === frameId
なときに，そこまでの
this.framesController.frames[frameId].imageData
が無駄になってしまうので，else で this.framesController.frames[frameId].imageData するなり，

let imageData = this.framesController.currentFrameId === frameId 
  ? this.framesController.canvasModel.getImageData()
   : this.framesController.frames[frameId].imageData;
(インデントは直して~)

なりでいかがでしょう．

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/93)_

**Comment by shundroid** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

_[js/view/sequence-view.js, line 88 [r3]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/93#-KHA61lXdjDRCQA6vIXI:-KHA61lXdjDRCQA6vIXJ:12902711) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/905fcf41d6873685417647a73ad4e32dd25e8f98/js/view/sequence-view.js#L88)):_
ぼくがやった記憶があります・・が、
ここのif文をなくして、EventListenerをThumbnail全体につけるのではなく、
Canvasにつけたほうがシンプルになると思います。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/93)_

**Comment by shundroid** [comment]
Reviewed 1 of 2 files at r4.
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/93)_

**Comment by shundroid** [comment]
Reviewed 1 of 2 files at r3.
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/93)_

**Comment by dadaa** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

_[js/frames-controller.js, line 30 [r5]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/93#-KHiPt97GxcDOpsx1hWN:-KHiPt97GxcDOpsx1hWO:2036325273) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/c1416428f73ad6e1efcf1294b335226ad8f982c0/js/frames-controller.js#L30)):_

> ``` JavaScript
> 
> // パラメータ id : どこの後ろに追加するのか（今は実装していない）
> FramesController.prototype.append = function(id) {
> ```

引数が frame id の場合，frameId で統一しましょう

---

_[js/frames-controller.js, line 37 [r5]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/93#-KHiQ6Yjl-WAmAnSMkj8:-KHiQ6Yjl-WAmAnSMkj9:1003495348) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/c1416428f73ad6e1efcf1294b335226ad8f982c0/js/frames-controller.js#L37)):_

> ``` JavaScript
> };
> 
> FramesController.prototype.remove = function(id) {
> ```

ここも frameId で統一しましょう

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/93)_

**Comment by shundroid** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

_[js/frames-controller.js, line 15 [r5]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/93#-KHiRD3RWZnzyvQxpoji:-KHiRD3Sx4U2_F_I8D2u:-1915343022) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/c1416428f73ad6e1efcf1294b335226ad8f982c0/js/frames-controller.js#L15)):_

> ``` JavaScript
>     updateCurrentFrameImageData();
>     this.currentFrameId = frameId;
>     this.canvasModel.updateCurrentFrameImageData(this.getCurrentFrame().imageData);
> ```

ここは直さなくていいっす～

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/93)_

**Comment by shundroid** [comment]
Reviewed 1 of 5 files at r2, 1 of 3 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/93)_

**Comment by dadaa** [comment]
Reviewed 1 of 3 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/93)_

**Comment by dadaa** [comment]
OK

<details><summary>

<i>Previously, nakamurataichi wrote…</i></summary>



> #### Thumbnail #77
> 
> </details>

---

Reviewed 1 of 2 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[js/frames-controller.js, line 30 [r5]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/93#-KHiPt97GxcDOpsx1hWN:-KHti0zIv94_Y_sNZXSc:5173665) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/c1416428f73ad6e1efcf1294b335226ad8f982c0/js/frames-controller.js#L30)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> 引数が frame id の場合，frameId で統一しましょう</details>
> OK

---

_[js/frames-controller.js, line 37 [r5]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/93#-KHiQ6Yjl-WAmAnSMkj8:-KHtiDnkdQIeM6MGqdiB:5173665) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/c1416428f73ad6e1efcf1294b335226ad8f982c0/js/frames-controller.js#L37)):_
<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> ここも frameId で統一しましょう</details>
> OK

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/93#-:-KHtikKN3sWXzWJ896EQ:5173665)_

**Comment by dadaa** [comment]
:lgtm:

<details><summary>

<i>Previously, dadaa wrote…</i></summary>



> OK</details>

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/93#-:-KHtitK_RXL1EfdwyRP-:1417088721)_

**Pull request merged**
