### PR TITLE
Trial new design

### PR DESCRIPTION
**Pull request by shundroid**
This change is [Reviewable](https://reviewable.io/reviews/comozilla/parapara-canvas-editor/57)

### CODE REVIEW

**Comment by shundroid** [comment]
@hrl7 レビューをよろしくお願いします。

**Comment by zigen** [comment]
Reviewed 13 of 14 files at r1.
Review status: 10 of 11 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/57)_

**Comment by zigen** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/57)_

**Comment by zigen** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

_[js/state.js, line 10 [r2]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/57#-KGb-84h2qsnR5lBnSyP:-KGb-84h2qsnR5lBnSyQ:-1400056081) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/4ed968861b4a23365ee7cad8f49fc6e9f137b162/js/state.js#L10)):_
newStateよりnextStateのほうがよさそう

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/57)_

**Comment by shundroid** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[js/state.js, line 10 [r2]](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/57#-KGb-84h2qsnR5lBnSyP:-KGb-skUyT8x7JU3Rdol:-2126080999) ([raw file](https://github.com/comozilla/parapara-canvas-editor/blob/4ed968861b4a23365ee7cad8f49fc6e9f137b162/js/state.js#L10)):_
直しますー

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/57)_

**Comment by zigen** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/parapara-canvas-editor/57)_

**Pull request merged**
